name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove custom .npmrc if exists
        run: rm -f .npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@11

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Replace private registry URLs in package-lock.json
        run: sed -i 's|https://nexus\.s2\.novomatic-tech\.com/repository/nexus-npm-proxy/|https://registry.npmjs.org/|g' package-lock.json

      - name: Debug environment
        run: |
          echo "=== Environment Debug ==="
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "NPM location: $(which npm)"
          echo "Node location: $(which node)"
          echo "Current directory: $(pwd)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"
          echo "=== Directory listing ==="
          ls -la

      - name: Install dependencies
        run: |
          set -x
          npm install 2>&1 | tee npm-install.log || echo "npm install failed with exit code $?"
          echo "Install completed"

      - name: Upload npm logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs-lint
          path: |
            npm-install.log
            ~/.npm/_logs/
          retention-days: 7
        continue-on-error: true

      - name: Run linter
        run: npm run lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove custom .npmrc if exists
        run: rm -f .npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@11

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Replace private registry URLs in package-lock.json
        run: sed -i 's|https://nexus\.s2\.novomatic-tech\.com/repository/nexus-npm-proxy/|https://registry.npmjs.org/|g' package-lock.json

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"

      - name: Install dependencies
        run: |
          npm install 2>&1 | tee npm-install.log
          echo "Install exit code: $?"

      - name: Upload npm logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs-unit-test
          path: |
            npm-install.log
            ~/.npm/_logs/
          retention-days: 7
        continue-on-error: true

      - name: Run unit tests with coverage
        run: npm run test:unit -- --coverage --run
        env:
          NODE_ENV: test

      - name: Upload unit test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 7

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove custom .npmrc if exists
        run: rm -f .npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@11

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Replace private registry URLs in package-lock.json
        run: sed -i 's|https://nexus\.s2\.novomatic-tech\.com/repository/nexus-npm-proxy/|https://registry.npmjs.org/|g' package-lock.json

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"

      - name: Install dependencies
        run: |
          npm install 2>&1 | tee npm-install.log
          echo "Install exit code: $?"

      - name: Upload npm logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs-e2e-test
          path: |
            npm-install.log
            ~/.npm/_logs/
          retention-days: 7
        continue-on-error: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NODE_ENV: test
          CI: true
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          E2E_EMAIL: ${{ secrets.E2E_EMAIL }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint, unit-test, e2e-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove custom .npmrc if exists
        run: rm -f .npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@11

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Replace private registry URLs in package-lock.json
        run: sed -i 's|https://nexus\.s2\.novomatic-tech\.com/repository/nexus-npm-proxy/|https://registry.npmjs.org/|g' package-lock.json

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"

      - name: Install dependencies
        run: |
          npm install 2>&1 | tee npm-install.log
          echo "Install exit code: $?"

      - name: Upload npm logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs-build
          path: |
            npm-install.log
            ~/.npm/_logs/
          retention-days: 7
        continue-on-error: true

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7
